GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmVkYW50IiwiaWF0IjoxNzY2OTM5OTA0fQ.kY3kGgpDgojatta42t-odg1DgWQTTeV5nFnV86GWoBQ


### 

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Vedant"
}